
<a href="<?=App::config('url')?>smjer/novi"
    class="success button expanded">Dodaj novi</a>

<table>
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Cijena</th>
            <th>Trajanje</th>
            <th>Upisnina</th>
            <th>Certificiran</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($smjerovi as $s): ?>
            <tr>
                <td><?=$s->naziv?></td>
                <td style="text-align: right;"><?=$s->cijena?></td>
                <td style="text-align: right;"><?=$s->trajanje?></td>
                <td style="text-align: right;"><?=$s->upisnina?></td>
                <td style="text-align: center;">
                    <i style="color: <?php echo $s->certificiran ? 'green' : 'red';  ?>;"
                            class="step fi-check size-48">
                </td>
                <td>
                    <a href="<?=App::config('url')?>smjer/promjena/<?=$s->sifra?>">
                        <i style="color: blue;" 
                        class="step fi-pencil size-36"></i>
                     </a>
                        &nbsp;&nbsp;
                     <a href="<?=App::config('url')?>smjer/brisanje/<?=$s->sifra?>">
                        <i style="color: red;" 
                        class="step fi-page-delete size-36"></i>
                     </a>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>