<div class="callout" 
 style="margin-top: 25px; height: 360px;">

	<input id="uvjet" type="text" placeholder="Dio imena ili prezimena polaznika">

    
    <div style="overflow: auto; max-height: 280px;">
        <table>
            <thead>
                <tr>
                    <th>Polaznik</th>
                    <th>Akcija</th>
                </tr>
            </thead>
            <tbody id="podaci">
                <?php foreach($e->polaznici as $p): ?>
                    <tr>
                        <td><?=$p->prezime?> <?=$p->ime?></td>
                        <td>
                            <a class="brisiPolaznika" href="#" id="p_<?=$p->sifra?>">
                                <i style="color: red;" 
                                class="step fi-page-delete size-36"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach;?>
            </tbody>
        </table>
    </div>
</div>